[targets.main]
artifacts = ['bin/bake']
# TODO: deps that are other targets
deps = ['**/*.go']
command = """
# TODO: how to pass the dep names into here, if required?
# maybe just put them in a bash array ${deps[@]}
mkdir -p bin
go build -o bin/bake .
"""
